In [1]:
import json
import pandas as pd

In [2]:
file_business, file_checkin, file_review, file_tip, file_user = [
    
    'sample_data/business.json',
    'sample_data/checkin.json',
    'sample_data/review.json',
    'sample_data/tip.json',
    'sample_data/user.json'

]

In [3]:
from time import time
t_start = time() # for cost time calculation
t0=time()

with open(file_business) as f:
    df_business = pd.DataFrame(json.loads(line) for line in f)
t1 = time()
print "loading business data cost: {0:4f}s". format(t1-t0)

loading business data cost: 7.528000s

In [4]:
df_business.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state
0,691 Richmond Rd,"{u'RestaurantsPriceRange2': 2, u'BusinessParki...",YDf95gJZaq05wvo7hTQbbQ,"[Shopping, Shopping Centers]",Richmond Heights,"{u'Monday': u'10:00-21:00', u'Tuesday': u'10:0...",1,41.541716,-81.493116,Richmond Town Square,,44143,17,2.0,OH
1,2824 Milton Rd,"{u'GoodForMeal': {u'dessert': False, u'latenig...",mLwM-h2YhXl2NCgdS84_Bw,"[Food, Soul Food, Convenience Stores, Restaura...",Charlotte,"{u'Monday': u'10:00-22:00', u'Tuesday': u'10:0...",0,35.236870,-80.741976,South Florida Style Chicken & Ribs,Eastland,28215,4,4.5,NC
2,337 Danforth Avenue,"{u'BusinessParking': {u'garage': False, u'stre...",v2WhjAB3PIBA8J8VxG3wEg,"[Food, Coffee & Tea]",Toronto,"{u'Monday': u'10:00-19:00', u'Tuesday': u'10:0...",0,43.677126,-79.353285,The Tea Emporium,Riverdale,M4K 1N7,7,4.5,ON
3,"7702 E Doubletree Ranch Rd, Ste 300",{},CVtCbSB1zUcUWg-9TNGTuQ,"[Professional Services, Matchmakers]",Scottsdale,"{u'Tuesday': u'9:00-17:00', u'Friday': u'9:00-...",1,33.565082,-111.916400,TRUmatch,,85258,3,3.0,AZ
4,4719 N 20Th St,"{u'GoodForMeal': {u'dessert': False, u'latenig...",duHFBe87uNSXImQmvBh87Q,"[Sandwiches, Restaurants]",Phoenix,{},0,33.505928,-112.038847,Blimpie,,85016,10,4.5,AZ

In [5]:
df_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156639 entries, 0 to 156638
Data columns (total 15 columns):
address         156639 non-null object
attributes      156639 non-null object
business_id     156639 non-null object
categories      156639 non-null object
city            156639 non-null object
hours           156639 non-null object
is_open         156639 non-null int64
latitude        156638 non-null float64
longitude       156638 non-null float64
name            156639 non-null object
neighborhood    156639 non-null object
postal_code     156639 non-null object
review_count    156639 non-null int64
stars           156639 non-null float64
state           156639 non-null object
dtypes: float64(3), int64(2), object(10)
memory usage: 17.9+ MB

In [6]:
# create pandas dataframe filters
cond_city = df_business['city'] == "Las Vegas"

# isnull bool

cond_category_not_null = ~df_business['categories'].isnull()

# restaurant in categories
# first, apply(str) convert categories to strings, then check if it contains restaurants

cond_category_restaurant = df_business['categories'].apply(str).str.contains("Restaurants")

In [7]:
# create filtered dataframe, name it df_filtered
df_filtered = df_business[cond_city & cond_category_not_null & cond_category_restaurant]

df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5682 entries, 58 to 156635
Data columns (total 15 columns):
address         5682 non-null object
attributes      5682 non-null object
business_id     5682 non-null object
categories      5682 non-null object
city            5682 non-null object
hours           5682 non-null object
is_open         5682 non-null int64
latitude        5682 non-null float64
longitude       5682 non-null float64
name            5682 non-null object
neighborhood    5682 non-null object
postal_code     5682 non-null object
review_count    5682 non-null int64
stars           5682 non-null float64
state           5682 non-null object
dtypes: float64(3), int64(2), object(10)
memory usage: 710.2+ KB

In [8]:
df_filtered.head()

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,neighborhood,postal_code,review_count,stars,state
58,2400 E Lake Mead Blvd,"{u'GoodForMeal': {u'dessert': False, u'latenig...",LDMCrFlGIFUN6L-FEFgzWg,"[Restaurants, American (Traditional), Mexican,...",Las Vegas,"{u'Monday': u'9:00-23:00', u'Tuesday': u'9:00-...",1,36.196203,-115.116799,El Pollo Loco,,89030,12,3.0,NV
64,4190 S Rainbow Blvd,"{u'RestaurantsPriceRange2': 1, u'RestaurantsAt...",QTH_XGh4rWYdd0fTW-tUDw,"[Mexican, Restaurants]",Las Vegas,{},0,36.112519,-115.242605,Baja Fresh Mexican Grill,Spring Valley,89103,7,3.5,NV
90,6325 E Russell Rd,"{u'BusinessAcceptsCreditCards': True, u'Restau...",DiA78qPtp6rfRNdomzjBbw,"[Chinese, Food, Convenience Stores, Restaurants]",Las Vegas,{},1,36.083384,-115.033995,Joshan Filipino Oriental Market,Southeast,89122,17,3.5,NV
107,"1203 E Charleston Blvd, Ste 140","{u'GoodForMeal': {u'dessert': False, u'latenig...",YTqtM2WFhcMZGeAGA08Cfg,"[Seafood, Restaurants, Specialty Food, Ethnic ...",Las Vegas,"{u'Monday': u'10:30-21:00', u'Tuesday': u'10:3...",1,36.159363,-115.135949,Mariscos Playa Escondida,Downtown,89104,330,4.5,NV
116,"South Point Hotel & Casino, 9777 S Las Vegas Blvd","{u'GoodForMeal': {u'dessert': False, u'latenig...",Oto60yDwk1z72WmfWEYrjg,"[Food, Restaurants, Mexican]",Las Vegas,"{u'Sunday': u'11:00-23:00', u'Wednesday': u'10...",1,36.012191,-115.173993,Baja Miguel's,Southeast,89183,175,3.0,NV

Keep relevant columns, business_id, name, categories, stars

In [9]:
selected_features = [u'business_id', u'name', u'categories', u'stars']

In [10]:
df_selected_business = df_filtered[selected_features]

In [11]:
df_selected_business.rename(columns={"stars":"avg_stars"}, inplace = True)

C:\Users\Lei Lei\Anaconda2\lib\site-packages\pandas\core\frame.py:2844: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [12]:
df_selected_business.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5682 entries, 58 to 156635
Data columns (total 4 columns):
business_id    5682 non-null object
name           5682 non-null object
categories     5682 non-null object
avg_stars      5682 non-null float64
dtypes: float64(1), object(3)
memory usage: 222.0+ KB

In [13]:
df_selected_business.head()

,business_id,name,categories,avg_stars
58,LDMCrFlGIFUN6L-FEFgzWg,El Pollo Loco,"[Restaurants, American (Traditional), Mexican,...",3.0
64,QTH_XGh4rWYdd0fTW-tUDw,Baja Fresh Mexican Grill,"[Mexican, Restaurants]",3.5
90,DiA78qPtp6rfRNdomzjBbw,Joshan Filipino Oriental Market,"[Chinese, Food, Convenience Stores, Restaurants]",3.5
107,YTqtM2WFhcMZGeAGA08Cfg,Mariscos Playa Escondida,"[Seafood, Restaurants, Specialty Food, Ethnic ...",4.5
116,Oto60yDwk1z72WmfWEYrjg,Baja Miguel's,"[Food, Restaurants, Mexican]",3.0

In [32]:
#save results to csv file
df_selected_business.to_csv("selected_business.csv", index = False, encoding = "utf-8")

In [ ]:
#load review dataset



from time import time
t_start = time() # for cost time calculation
t0=time()

with open(file_review) as f:
    df_review = pd.DataFrame(json.loads(line) for line in f)
t1 = time()
print "loading review data cost: {0:4f}s". format(t1-t0)